=== TIWM-G06-2020/Lobile-TrabalhoTI/src/xml/telemoveis.xsd
<?xml version="1.0"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.org/telemoveis"
    xmlns="http://www.example.org/telemoveis"
    elementFormDefault="qualified">

    <xs:element name="telemoveis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Telemovel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="ecra">
                                <xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="4"/>
										<xs:totalDigits value="2" />
										<xs:fractionDigits value="2"/>
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="99"/>
                                        <xs:totalDigits value="2" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="armazenamento">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                        <xs:totalDigits value="4" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="camara">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                        <xs:totalDigits value="1" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="resolucao">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="200"/>
                                        <xs:totalDigits value="3" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="bateria">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="50000"/>
                                        <xs:totalDigits value="5" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="preco">
									<xs:simpleType>
										<xs:restriction base="xs:decimal">
										  <xs:minInclusive value="0"/>
										  <xs:totalDigits value="10" />
										  <xs:fractionDigits value="2"/>
										</xs:restriction>
									  </xs:simpleType>
								</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Telemovel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="ecra">
                                <xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="4"/>
										<xs:totalDigits value="2" />
										<xs:fractionDigits value="2"/>
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="99"/>
                                        <xs:totalDigits value="2" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="armazenamento">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                        <xs:totalDigits value="4" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="camara">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                        <xs:totalDigits value="1" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="resolucao">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="200"/>
                                        <xs:totalDigits value="3" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="bateria">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="50000"/>
                                        <xs:totalDigits value="5" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="preco">
									<xs:simpleType>
										<xs:restriction base="xs:decimal">
										  <xs:minInclusive value="0"/>
										  <xs:totalDigits value="10" />
										  <xs:fractionDigits value="2"/>
										</xs:restriction>
									  </xs:simpleType>
								</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Telemovel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="ecra">
                                <xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="4"/>
										<xs:totalDigits value="2" />
										<xs:fractionDigits value="2"/>
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="99"/>
                                        <xs:totalDigits value="2" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="armazenamento">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                        <xs:totalDigits value="4" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="camara">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                        <xs:totalDigits value="1" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="resolucao">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="200"/>
                                        <xs:totalDigits value="3" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="bateria">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="50000"/>
                                        <xs:totalDigits value="5" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="preco">
									<xs:simpleType>
										<xs:restriction base="xs:decimal">
										  <xs:minInclusive value="0"/>
										  <xs:totalDigits value="10" />
										  <xs:fractionDigits value="2"/>
										</xs:restriction>
									  </xs:simpleType>
								</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Telemovel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="ecra">
                                <xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="4"/>
										<xs:totalDigits value="2" />
										<xs:fractionDigits value="2"/>
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="99"/>
                                        <xs:totalDigits value="2" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="armazenamento">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                        <xs:totalDigits value="4" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="camara">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                        <xs:totalDigits value="1" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="resolucao">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="200"/>
                                        <xs:totalDigits value="3" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="bateria">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="50000"/>
                                        <xs:totalDigits value="5" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="preco">
									<xs:simpleType>
										<xs:restriction base="xs:decimal">
										  <xs:minInclusive value="0"/>
										  <xs:totalDigits value="10" />
										  <xs:fractionDigits value="2"/>
										</xs:restriction>
									  </xs:simpleType>
								</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Telemovel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="ecra">
                                <xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="4"/>
										<xs:totalDigits value="2" />
										<xs:fractionDigits value="2"/>
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="99"/>
                                        <xs:totalDigits value="2" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="armazenamento">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                        <xs:totalDigits value="4" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="camara">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                        <xs:totalDigits value="1" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="resolucao">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="200"/>
                                        <xs:totalDigits value="3" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="bateria">
                                <xs:simpleType>
									<xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="50000"/>
                                        <xs:totalDigits value="5" />
									</xs:restriction>
								</xs:simpleType>
                            </xs:element>
                            <xs:element name="preco">
									<xs:simpleType>
										<xs:restriction base="xs:decimal">
										  <xs:minInclusive value="0"/>
										  <xs:totalDigits value="10" />
										  <xs:fractionDigits value="2"/>
										</xs:restriction>
									  </xs:simpleType>
								</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TIWM-G06-2020/Lobile-TrabalhoTI/src/xml/telemoveis.xml
<?xml version="1.0"?> 
<telemoveis xmlns="http://www.example.org/telemoveis" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/telemoveis telemoveis.xsd">
        <Telemovel>
            <marca>Iphone</marca>
            <nome>11</nome>
            <ecra>5</ecra>
            <ram>12</ram>
            <armazenamento>256</armazenamento>
            <camara>2</camara>
            <resolucao>64</resolucao>
            <bateria>4000</bateria>
            <preco>800.00</preco>
        </Telemovel>
        <Telemovel>
            <marca>Iphone</marca>
            <nome>11 Pro</nome>
            <ecra>6</ecra>
            <ram>16</ram>
            <armazenamento>256</armazenamento>
            <camara>3</camara>
            <resolucao>64</resolucao>
            <bateria>5500</bateria>
            <preco>1000.00</preco>
        </Telemovel>
        <Telemovel>
            <marca>Iphone</marca>
            <nome>12</nome>
            <ecra>5.5</ecra>
            <ram>16</ram>
            <armazenamento>512</armazenamento>
            <camara>3</camara>
            <resolucao>64</resolucao>
            <bateria>6000</bateria>
            <preco>1200.00</preco>
        </Telemovel>
        <Telemovel>
            <marca>Xiaomi</marca>
            <nome>Redmi</nome>
            <ecra>7.2</ecra>
            <ram>16</ram>
            <armazenamento>512</armazenamento>
            <camara>1</camara>
            <resolucao>64</resolucao>
            <bateria>3000</bateria>
            <preco>250.00</preco>
        </Telemovel>
        <Telemovel>
            <marca>Huawey</marca>
            <nome>P3</nome>
            <ecra>6.3</ecra>
            <ram>16</ram>
            <armazenamento>512</armazenamento>
            <camara>2</camara>
            <resolucao>64</resolucao>
            <bateria>4500</bateria>
            <preco>120.00</preco>
        </Telemovel>
</telemoveis>
